In [1]:
from model.attention import FlashGroupQueryAttention, GroupQueryAttention, compute_rope_params
import torch
import time
# from model.utils import co


In [2]:
d_model=24
g=torch.Generator().manual_seed(123)
torch.manual_seed(123)
cfg={}
import torch
batch_size=4
seq_len=4096
emb_dim=512
cfg['emb_dim']=emb_dim
cfg['dtype']=torch.float32
cfg['num_heads']=4
cfg["num_kv_groups"]=2
cfg["head_dim"]=cfg['emb_dim']//cfg['num_heads']
B=torch.randn(batch_size, seq_len,emb_dim, dtype=cfg['dtype'], generator=g)
gq=GroupQueryAttention(d_in=cfg["emb_dim"],num_kv_groups=cfg["num_kv_groups"], num_heads=cfg["num_heads"],head_dim=cfg["head_dim"], dtype=cfg["dtype"])
start_pos=0
end_pos=start_pos+B.shape[1]
mask=torch.triu(
    torch.ones(end_pos,end_pos,device=B.device, dtype=torch.bool), diagonal=1
)[start_pos:end_pos, :end_pos]
print(mask)
print(gq)
start=time.time()
cos, sin=compute_rope_params(head_dim=cfg["head_dim"],context_length=seq_len)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
B = B.to(device)
gq = gq.to(device)
cos = cos.to(device)
sin = sin.to(device)
mask = mask.to(device)
print(gq(B, mask,cos, sin, start_pos=start_pos))
print("logger timer : ", time.time()-start)

tensor([[False,  True,  True,  ...,  True,  True,  True],
        [False, False,  True,  ...,  True,  True,  True],
        [False, False, False,  ...,  True,  True,  True],
        ...,
        [False, False, False,  ..., False,  True,  True],
        [False, False, False,  ..., False, False,  True],
        [False, False, False,  ..., False, False, False]])
GroupQueryAttention(
  (W_query): Linear(in_features=512, out_features=512, bias=False)
  (W_key): Linear(in_features=512, out_features=256, bias=False)
  (W_value): Linear(in_features=512, out_features=256, bias=False)
  (out_proj): Linear(in_features=512, out_features=512, bias=False)
)
(tensor([[[-1.2828e-01, -7.1364e-01, -4.1895e-02,  ...,  2.5542e-01,
          -7.5122e-02,  1.2389e-01],
         [-6.6884e-02, -3.4429e-01, -1.3065e-01,  ...,  9.1892e-02,
           1.0420e-01,  4.6886e-02],
         [-1.0312e-01, -4.0249e-01, -3.1868e-01,  ...,  1.0749e-03,
          -1.2751e-01,  1.1136e-02],
         ...,
         [ 7.4211e

In [3]:
d_model=24
g=torch.Generator().manual_seed(123)
torch.manual_seed(123)
cfg={}
import torch
batch_size=4
seq_len=4096
emb_dim=512
cfg['emb_dim']=emb_dim
cfg['dtype']=torch.float32
cfg['num_heads']=4
cfg["num_kv_groups"]=2
cfg["head_dim"]=cfg['emb_dim']//cfg['num_heads']
B=torch.randn(batch_size, seq_len,emb_dim, dtype=cfg['dtype'], generator=g)
gq=FlashGroupQueryAttention(d_in=cfg["emb_dim"],num_kv_groups=cfg["num_kv_groups"], num_heads=cfg["num_heads"],head_dim=cfg["head_dim"], dtype=cfg["dtype"])
start_pos=0
end_pos=start_pos+B.shape[1]
mask=torch.triu(
    torch.ones(end_pos,end_pos,device=B.device, dtype=torch.bool), diagonal=1
)[start_pos:end_pos, :end_pos]
print(mask)
print(gq)
start=time.time()
cos, sin=compute_rope_params(head_dim=cfg["head_dim"],context_length=seq_len)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
B = B.to(device)
gq = gq.to(device)
cos = cos.to(device)
sin = sin.to(device)
mask = mask.to(device)
print(gq(B, mask,cos, sin, start_pos=start_pos))
print("logger timer : ", time.time()-start)

tensor([[False,  True,  True,  ...,  True,  True,  True],
        [False, False,  True,  ...,  True,  True,  True],
        [False, False, False,  ...,  True,  True,  True],
        ...,
        [False, False, False,  ..., False,  True,  True],
        [False, False, False,  ..., False, False,  True],
        [False, False, False,  ..., False, False, False]])
FlashGroupQueryAttention(
  (W_query): Linear(in_features=512, out_features=512, bias=False)
  (W_key): Linear(in_features=512, out_features=256, bias=False)
  (W_value): Linear(in_features=512, out_features=256, bias=False)
  (out_proj): Linear(in_features=512, out_features=512, bias=False)
)
(tensor([[[-1.2828e-01, -7.1364e-01, -4.1895e-02,  ...,  2.5542e-01,
          -7.5122e-02,  1.2389e-01],
         [-6.6884e-02, -3.4429e-01, -1.3065e-01,  ...,  9.1892e-02,
           1.0420e-01,  4.6886e-02],
         [-1.0312e-01, -4.0249e-01, -3.1868e-01,  ...,  1.0749e-03,
          -1.2751e-01,  1.1136e-02],
         ...,
         [ 7.